const mongoose = require('mongoose')
const { dbURI } = require('../config/environment')
const Category = require('../models/category')

mongoose.connect(dbURI, { useNewUrlParser: true}, (err, db) => {

  //this deletes the current database
  db.dropDatabase()

  Category.create([
    {	'name': 'Algerian'	},
    {	'name': 'Allergy-Free'	},
    {	'name': 'American'	},
    {	'name': 'BBQ Food'	},
    {	'name': 'Belgian'	},
    {	'name': 'Brazilian'	},
    {	'name': 'Bread & Doughs'	},
    {	'name': 'Breakfast'	},
    {	'name': 'British'	},
    {	'name': 'Burgers'	},
    {	'name': 'Cajun'	},
    {	'name': 'Cakes'	},
    {	'name': 'Canadian'	},
    {	'name': 'Caribbean'	},
    {	'name': 'Casserole'	},
    {	'name': 'Cheese'	},
    {	'name': 'Chinese'	},
    {	'name': 'Cocktails'	},
    {	'name': 'Cookies'	},
    {	'name': 'Cuban'	},
    {	'name': 'Curry'	},
    {	'name': 'Diabetic'	},
    {	'name': 'Dinner Party'	},
    {	'name': 'Dinner'	},
    {	'name': 'Drinks'	},
    {	'name': 'Egyptian'	},
    {	'name': 'Energy Boosting'	},
    {	'name': 'Ethiopian'	},
    {	'name': 'Fast Food'	},
    {	'name': 'Fine Dining'	},
    {	'name': 'French'	},
    {	'name': 'German'	},
    {	'name': 'Gluten-Free'	},
    {	'name': 'Greek'	},
    {	'name': 'Hawaiian'	},
    {	'name': 'Healthy'	},
    {	'name': 'Hearty'	},
    {	'name': 'High-Protein'	},
    {	'name': 'Hipster'	},
    {	'name': 'Indian'	},
    {	'name': 'Irish'	},
    {	'name': 'Italian'	},
    {	'name': 'Japanese'	},
    {	'name': 'Kenyan'	},
    {	'name': 'Kitsch'	},
    {	'name': 'Korean'	},
    {	'name': 'Lacto-Ovo Vegetarians'	},
    {	'name': 'Lacto-Vegetarian'	},
    {	'name': 'Lactose-Free'	},
    {	'name': 'Latvian'	},
    {	'name': 'Lebanese'	},
    {	'name': 'Libyan'	},
    {	'name': 'Low-Carb'	},
    {	'name': 'Lunch'	},
    {	'name': 'Mediterranean'	},
    {	'name': 'Mexican'	},
    {	'name': 'Moroccan'	},
    {	'name': 'Muffins'	},
    {	'name': 'Nigerian'	},
    {	'name': 'No-Sodium'	},
    {	'name': 'Non-Spicy'	},
    {	'name': 'Nut-Free'	},
    {	'name': 'Occasions'	},
    {	'name': 'One Pot'	},
    {	'name': 'Ovo-Vegetarian'	},
    {	'name': 'Paleo'	},
    {	'name': 'Pancakes'	},
    {	'name': 'Pasta & Risotto'	},
    {	'name': 'Pasta Bakes'	},
    {	'name': 'Peruvian'	},
    {	'name': 'Pescetarians'	},
    {	'name': 'Pizza'	},
    {	'name': 'Polish'	},
    {	'name': 'Portuguese'	},
    {	'name': 'Puddings & Desserts'	},
    {	'name': 'Quick & Easy'	},
    {	'name': 'Roast'	},
    {	'name': 'Romantic'	},
    {	'name': 'Russian'	},
    {	'name': 'Salad'	},
    {	'name': 'Salvadorian'	},
    {	'name': 'Sandwiches & Wraps'	},
    {	'name': 'Sauces & Condiments'	},
    {	'name': 'Scottish'	},
    {	'name': 'Sharing'	},
    {	'name': 'Snacks'	},
    {	'name': 'Soup'	},
    {	'name': 'Spanish'	},
    {	'name': 'Spicy'	},
    {	'name': 'Steak'	},
    {	'name': 'Stew'	},
    {	'name': 'Swedish'	},
    {	'name': 'Tapas'	},
    {	'name': 'Thai'	},
    {	'name': 'Tibetan'	},
    {	'name': 'Turkish'	},
    {	'name': 'Vegan'	},
    {	'name': 'Vegetarian'	},
    {	'name': 'Vietnamese'	},
    {	'name': 'Welsh'	}
  ])
    .then(categories => console.log(`${categories.length} categories created`))
    .catch(err => console.log(err))
    .finally(() => mongoose.connection.close())
})
